### ISSUE TITLE
Build error: 'vector' does not name a type in graph.cc

### ISSUE THREAD

**Issue by caykara** [MIT-SPARK/TEASER-plusplus#200]
Hi,

I'm encountering a build error when trying to compile on a fresh Ubuntu 20.04. Here's the error output:

```
[ 37%] Building CXX object teaser/CMakeFiles/teaser_registration.dir/src/graph.cc.o
/home/username/temp/TEASER-plusplus/teaser/src/graph.cc:12:1: error: ‘vector’ does not name a type
   12 | vector<int> teaser::MaxCliqueSolver::findMaxClique(teaser::Graph graph) {
      | ^~~~~~
make[2]: *** [teaser/CMakeFiles/teaser_registration.dir/build.make:89: teaser/CMakeFiles/teaser_registration.dir/src/graph.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:562: teaser/CMakeFiles/teaser_registration.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Environment:

| Component         | Version   |
|------------------|----------------------------------------|
| OS  | Ubuntu 20.04.6 (tested on 3 machines)  |
| g++   | 9.4.0 |
| cmake | 3.16.3   |
| libeigen3-dev | 3.3.7-2  |
| libboost-all-dev | 1.71.0.0ubuntu2  |

Could you please take a look and suggest a fix?
Thank you!

**Comment by jingnanshi** [comment]
should be fixed now
